### ISSUE TITLE
Add support for tables

### ISSUE THREAD

**Issue by machour** [smartkarma/react-native-jumbo-html#1]
### Expected behaviour

Using this HTML, I'm expecting to see a table of 2 rows each containing 2 columns:

```html
<table>
  <tr style="background:green">
    <td>prop</td>
    <td>bar</td>
    </tr>
  <tr style="background:red">
    <td>prop</td>
    <td>bar</td>
    </tr>
  </table>
```

### Actual behaviour

A 4 rows element is displayed

### Code sample, screenshots

<img width="526" alt="screen shot 2018-02-11 at 11 19 11 am" src="https://user-images.githubusercontent.com/304450/36072290-6cd2f64a-0f1d-11e8-95ac-4819bad4b4f1.png">

### What have you tried

I dived into the code a bit, in `render-native.js`, moving `td` and `th` from BLOCK_TAGS to INLINE_TAGS helps a bit, but it's not enough.

I think using a library like `react-native-table-component` could help.

**Comment by usrbowe** [comment]
We actually have an implementation for table rendering, but it was custom made for our specific use case. 
I will try to extract the basic logic and make it available in this repo.
